const questions = [
    { category: "Animals", question: "What is the fastest land animal?", options: ["Cheetah", "Lion", "Tiger", "Leopard"], answer: 0 },
    { category: "Animals", question: "Which animal is known as the King of the Jungle?", options: ["Lion", "Elephant", "Tiger", "Cheetah"], answer: 0 },
    { category: "Animals", question: "What is the largest mammal?", options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], answer: 1 },
    { category: "Animals", question: "Which bird is a symbol of peace?", options: ["Eagle", "Sparrow", "Dove", "Owl"], answer: 2 },
    { category: "Animals", question: "Which animal has a trunk?", options: ["Rhinoceros", "Elephant", "Hippopotamus", "Giraffe"], answer: 1 },
    { category: "Animals", question: "Which animal is known for its ability to change color?", options: ["Octopus", "Chameleon", "Cuttlefish", "Frog"], answer: 1 },
    { category: "Animals", question: "What is the tallest land animal?", options: ["Elephant", "Giraffe", "Kangaroo", "Ostrich"], answer: 1 },
    { category: "Animals", question: "Which of the following animals is a marsupial?", options: ["Kangaroo", "Lion", "Horse", "Panda"], answer: 0 },
    { category: "Animals", question: "What is a group of lions called?", options: ["Herd", "Flock", "Pack", "Pride"], answer: 3 },
    { category: "Animals", question: "Which animal is known to have a strong memory?", options: ["Dolphin", "Elephant", "Whale", "Horse"], answer: 1 },
    { category: "Animals", question: "What is the largest species of penguin?", options: ["Emperor Penguin", "King Penguin", "Adelie Penguin", "Chinstrap Penguin"], answer: 0 },
    { category: "Animals", question: "Which animal is known to play dead to avoid predators?", options: ["Rabbit", "Possum", "Snake", "Cat"], answer: 1 },
    { category: "Animals", question: "Which bird can fly backwards?", options: ["Eagle", "Hummingbird", "Sparrow", "Owl"], answer: 1 },
    { category: "Animals", question: "Which animal is known as the Ship of the Desert?", options: ["Camel", "Elephant", "Horse", "Donkey"], answer: 0 },
    { category: "Animals", question: "What is the only mammal capable of true flight?", options: ["Bat", "Eagle", "Flying Squirrel", "Penguin"], answer: 0 },
    { category: "Animals", question: "Which animal can sleep standing up?", options: ["Cow", "Horse", "Giraffe", "All of the above"], answer: 3 },
    { category: "Animals", question: "What is a baby kangaroo called?", options: ["Calf", "Cub", "Joey", "Foal"], answer: 2 },
    { category: "Animals", question: "Which is the fastest swimming bird?", options: ["Penguin", "Seagull", "Duck", "Puffin"], answer: 0 },
    { category: "Animals", question: "What is the largest species of shark?", options: ["Great White", "Hammerhead", "Tiger Shark", "Whale Shark"], answer: 3 },
    { category: "Animals", question: "What type of animal is a Komodo dragon?", options: ["Lizard", "Snake", "Crocodile", "Turtle"], answer: 0 },
    { category: "Animals", question: "Which animal can regrow its limbs?", options: ["Starfish", "Octopus", "Lobster", "Crab"], answer: 0 },
    { category: "Animals", question: "What is the smallest bird in the world?", options: ["Sparrow", "Robin", "Bee Hummingbird", "Finch"], answer: 2 },
    { category: "Animals", question: "Which animal has the longest lifespan?", options: ["Elephant", "Blue Whale", "Giant Tortoise", "Shark"], answer: 2 },
    { category: "Animals", question: "Which of these animals is cold-blooded?", options: ["Penguin", "Snake", "Kangaroo", "Eagle"], answer: 1 },
    { category: "Animals", question: "What is the slowest animal?", options: ["Snail", "Sloth", "Turtle", "Caterpillar"], answer: 1 },
    { category: "Animals", question: "Which animal is known for building dams?", options: ["Beaver", "Otter", "Duck", "Swan"], answer: 0 },
    { category: "Animals", question: "What type of animal is a Flemish Giant?", options: ["Rabbit", "Horse", "Dog", "Cat"], answer: 0 },
    { category: "Animals", question: "Which mammal lives the longest?", options: ["Elephant", "Human", "Blue Whale", "Bowhead Whale"], answer: 3 },
    { category: "Animals", question: "Which animal is known as man's best friend?", options: ["Dog", "Cat", "Horse", "Parrot"], answer: 0 },
    { category: "Animals", question: "Which animal can live both in water and on land?", options: ["Dolphin", "Frog", "Penguin", "Seal"], answer: 1 },
    { category: "Animals", question: "Which of these is the largest species of cat?", options: ["Lion", "Cheetah", "Tiger", "Leopard"], answer: 2 },
    { category: "Animals", question: "Which animal has the most legs?", options: ["Octopus", "Crab", "Millipede", "Spider"], answer: 2 },
    { category: "Animals", question: "What is a female deer called?", options: ["Buck", "Doe", "Fawn", "Stag"], answer: 1 },
    { category: "Animals", question: "Which mammal is known for laying eggs?", options: ["Platypus", "Bat", "Whale", "Koala"], answer: 0 },
    { category: "Animals", question: "Which animal is famous for its black and white stripes?", options: ["Zebra", "Tiger", "Panda", "Skunk"], answer: 0 },
    { category: "Animals", question: "Which animal produces pearls?", options: ["Oyster", "Lobster", "Crab", "Shrimp"], answer: 0 },
    { category: "Animals", question: "Which bird is known for its beautiful tail feathers?", options: ["Peacock", "Flamingo", "Parrot", "Ostrich"], answer: 0 },
    { category: "Animals", question: "What is the smallest species of dog?", options: ["Chihuahua", "Poodle", "Bulldog", "Beagle"], answer: 0 },
    { category: "Animals", question: "Which of these animals does not have a backbone?", options: ["Frog", "Starfish", "Shark", "Lizard"], answer: 1 },
    { category: "Animals", question: "Which bird is often associated with delivering babies?", options: ["Stork", "Eagle", "Pigeon", "Penguin"], answer: 0 },
    { category: "Animals", question: "What do pandas primarily eat?", options: ["Bamboo", "Leaves", "Grass", "Insects"], answer: 0 },
    { category: "Animals", question: "Which animal has the strongest bite force?", options: ["Crocodile", "Lion", "Wolf", "Shark"], answer: 0 },
    { category: "Animals", question: "What is the only poisonous mammal?", options: ["Bat", "Platypus", "Shrew", "Rat"], answer: 1 },
    { category: "Animals", question: "Which animal is known for its laughter-like call?", options: ["Hyena", "Kookaburra", "Monkey", "Owl"], answer: 0 },
    { category: "Animals", question: "Which animal's scientific name is Panthera leo?", options: ["Tiger", "Leopard", "Lion", "Cheetah"], answer: 2 },
    { category: "Animals", question: "Which animal is considered sacred in India?", options: ["Elephant", "Lion", "Tiger", "Cow"], answer: 3 },
    { category: "Animals", question: "Which animal is the symbol of the WWF?", options: ["Panda", "Elephant", "Lion", "Tiger"], answer: 0 },
    { category: "Animals", question: "What is a baby goose called?", options: ["Gosling", "Duckling", "Chick", "Pup"], answer: 0 },
    { category: "Animals", question: "Which animal can run up to 70 mph?", options: ["Cheetah", "Horse", "Lion", "Greyhound"], answer: 0 },

    { category: "Car Brands", question: "Which car brand is known for its logo featuring four rings?", options: ["BMW", "Audi", "Mercedes-Benz", "Volkswagen"], answer: 1 },
    { category: "Car Brands", question: "Which car manufacturer produces the Mustang?", options: ["Ford", "Chevrolet", "Dodge", "Nissan"], answer: 0 },
    { category: "Car Brands", question: "Which Italian car brand uses a prancing horse as its logo?", options: ["Ferrari", "Lamborghini", "Maserati", "Alfa Romeo"], answer: 0 },
    { category: "Car Brands", question: "Which German car brand’s logo features a propeller?", options: ["Audi", "BMW", "Porsche", "Mercedes-Benz"], answer: 1 },
    { category: "Car Brands", question: "Which car company produces the 911 sports car?", options: ["Ferrari", "BMW", "Porsche", "Lamborghini"], answer: 2 },
    { category: "Car Brands", question: "Which Japanese car brand's logo is a stylized 'T'?", options: ["Honda", "Toyota", "Nissan", "Mazda"], answer: 1 },
    { category: "Car Brands", question: "Which car brand's logo features a raging bull?", options: ["Ferrari", "Lamborghini", "Maserati", "Pagani"], answer: 1 },
    { category: "Car Brands", question: "Which car brand produces the F-150 truck?", options: ["Ram", "Chevrolet", "Ford", "Toyota"], answer: 2 },
    { category: "Car Brands", question: "Which South Korean car brand's logo features a stylized 'H'?", options: ["Kia", "Hyundai", "Genesis", "Daewoo"], answer: 1 },
    { category: "Car Brands", question: "Which Swedish car brand is known for its focus on safety?", options: ["Volvo", "Saab", "Koenigsegg", "Scania"], answer: 0 },
    { category: "Car Brands", question: "Which luxury car brand is owned by Toyota?", options: ["Acura", "Infiniti", "Lexus", "Cadillac"], answer: 2 },
    { category: "Car Brands", question: "Which car company produces the Civic?", options: ["Toyota", "Nissan", "Honda", "Mazda"], answer: 2 },
    { category: "Car Brands", question: "Which German car brand is known for its luxury and performance?", options: ["Audi", "BMW", "Mercedes-Benz", "All of the above"], answer: 3 },
    { category: "Car Brands", question: "Which car brand has a lion in its logo?", options: ["Peugeot", "Jaguar", "Lexus", "Ford"], answer: 0 },
    { category: "Car Brands", question: "Which car manufacturer produces the Corvette?", options: ["Ford", "Chevrolet", "Dodge", "BMW"], answer: 1 },
    { category: "Car Brands", question: "Which luxury car brand is British?", options: ["Jaguar", "Lexus", "Ferrari", "Audi"], answer: 0 },
    { category: "Car Brands", question: "Which car manufacturer produces the Camry?", options: ["Honda", "Toyota", "Nissan", "Hyundai"], answer: 1 },
    { category: "Car Brands", question: "Which Italian car brand's logo features a trident?", options: ["Maserati", "Ferrari", "Lamborghini", "Pagani"], answer: 0 },
    { category: "Car Brands", question: "Which German brand produces the Beetle?", options: ["BMW", "Audi", "Mercedes-Benz", "Volkswagen"], answer: 3 },
    { category: "Car Brands", question: "Which car manufacturer produces the S-Class?", options: ["Audi", "BMW", "Mercedes-Benz", "Volvo"], answer: 2 },
    { category: "Car Brands", question: "Which car brand produces the electric Model S?", options: ["Chevrolet", "Tesla", "Ford", "Nissan"], answer: 1 },
    { category: "Car Brands", question: "Which British car brand is known for its Mini Cooper?", options: ["Jaguar", "Bentley", "Mini", "Rolls-Royce"], answer: 2 },
    { category: "Car Brands", question: "Which car brand produces the Challenger?", options: ["Chevrolet", "Ford", "Dodge", "Tesla"], answer: 2 },
    { category: "Car Brands", question: "Which luxury car brand is associated with Bentley?", options: ["Volkswagen", "BMW", "Ford", "Toyota"], answer: 0 },
    { category: "Car Brands", question: "Which car manufacturer produces the Altima?", options: ["Honda", "Nissan", "Toyota", "Hyundai"], answer: 1 },
    { category: "Car Brands", question: "Which car brand uses the slogan 'The Ultimate Driving Machine'?", options: ["Mercedes-Benz", "Audi", "BMW", "Lexus"], answer: 2 },
    { category: "Car Brands", question: "Which car manufacturer produces the Accord?", options: ["Toyota", "Honda", "Nissan", "Mazda"], answer: 1 },
    { category: "Car Brands", question: "Which car brand's logo is a three-pointed star?", options: ["Audi", "Mercedes-Benz", "BMW", "Volkswagen"], answer: 1 },
    { category: "Car Brands", question: "Which luxury car brand is owned by Ford?", options: ["Lincoln", "Cadillac", "Buick", "Infiniti"], answer: 0 },
    { category: "Car Brands", question: "Which American car brand produces the Ram truck?", options: ["Chevrolet", "Ford", "Dodge", "GMC"], answer: 2 },
    { category: "Car Brands", question: "Which car manufacturer is known for producing hybrids like the Prius?", options: ["Honda", "Ford", "Toyota", "Hyundai"], answer: 2 },
    { category: "Car Brands", question: "Which car brand is known for its 'Zoom-Zoom' slogan?", options: ["Toyota", "Mazda", "Honda", "Ford"], answer: 1 },
    { category: "Car Brands", question: "Which luxury car brand produces the Escalade?", options: ["Cadillac", "Lincoln", "BMW", "Mercedes-Benz"], answer: 0 },
    { category: "Car Brands", question: "Which car brand is famous for its Wrangler SUV?", options: ["Jeep", "Ford", "Chevrolet", "Ram"], answer: 0 },
    { category: "Car Brands", question: "Which car brand is associated with the Impala?", options: ["Ford", "Chevrolet", "Nissan", "Honda"], answer: 1 },
    { category: "Car Brands", question: "Which car manufacturer produces the Range Rover?", options: ["Jeep", "Land Rover", "Ford", "Toyota"], answer: 1 },
    { category: "Car Brands", question: "Which car brand is known for producing the Escudo?", options: ["Suzuki", "Mazda", "Hyundai", "Toyota"], answer: 0 },
    { category: "Car Brands", question: "Which Italian car brand produces the Aventador?", options: ["Ferrari", "Maserati", "Lamborghini", "Pagani"], answer: 2 },
    { category: "Car Brands", question: "Which American car brand's logo features a blue oval?", options: ["Chevrolet", "Ford", "GMC", "Dodge"], answer: 1 },
    { category: "Car Brands", question: "Which car brand produces the Cherokee?", options: ["Toyota", "Jeep", "Ford", "Chevrolet"], answer: 1 },
    { category: "Car Brands", question: "Which British luxury car brand produces the Phantom?", options: ["Bentley", "Rolls-Royce", "Jaguar", "Aston Martin"], answer: 1 },
    { category: "Car Brands", question: "Which French car brand's logo features a double chevron?", options: ["Peugeot", "Citroën", "Renault", "Bugatti"], answer: 1 },
    { category: "Car Brands", question: "Which German car brand produces the Panamera?", options: ["Audi", "BMW", "Mercedes-Benz", "Porsche"], answer: 3 },
    { category: "Car Brands", question: "Which car brand is known for the Miata?", options: ["Toyota", "Mazda", "Honda", "Hyundai"], answer: 1 },
    { category: "Car Brands", question: "Which car manufacturer produces the Clio?", options: ["Peugeot", "Citroën", "Renault", "Fiat"], answer: 2 },
    { category: "Car Brands", question: "Which car brand is known for the Leaf electric vehicle?", options: ["Toyota", "Nissan", "Hyundai", "Ford"], answer: 1 },
    { category: "Car Brands", question: "Which luxury car brand produces the Ghost?", options: ["Bentley", "Rolls-Royce", "Jaguar", "Aston Martin"], answer: 1 },

    { category: "Cities", question: "Which city is known as the 'Big Apple'?", options: ["Los Angeles", "Chicago", "New York City", "Miami"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of France?", options: ["Rome", "Madrid", "Paris", "Berlin"], answer: 2 },
    { category: "Cities", question: "Which city hosted the 2020 Summer Olympics?", options: ["Tokyo", "Rio de Janeiro", "London", "Beijing"], answer: 0 },
    { category: "Cities", question: "Which city is famous for the Golden Gate Bridge?", options: ["Los Angeles", "San Francisco", "San Diego", "Seattle"], answer: 1 },
    { category: "Cities", question: "Which city is the capital of Japan?", options: ["Kyoto", "Osaka", "Tokyo", "Hiroshima"], answer: 2 },
    { category: "Cities", question: "Which city is home to the Eiffel Tower?", options: ["Berlin", "Madrid", "Paris", "Rome"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of Australia?", options: ["Sydney", "Melbourne", "Brisbane", "Canberra"], answer: 3 },
    { category: "Cities", question: "Which city is known for its canals and gondolas?", options: ["Rome", "Venice", "Florence", "Milan"], answer: 1 },
    { category: "Cities", question: "Which city is the capital of Germany?", options: ["Munich", "Berlin", "Hamburg", "Frankfurt"], answer: 1 },
    { category: "Cities", question: "Which city is the capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], answer: 3 },
    { category: "Cities", question: "Which city is the capital of the United States?", options: ["New York", "Los Angeles", "Washington D.C.", "Chicago"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of Egypt?", options: ["Alexandria", "Cairo", "Giza", "Luxor"], answer: 1 },
    { category: "Cities", question: "Which city is famous for the Colosseum?", options: ["Paris", "Athens", "Rome", "Florence"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of India?", options: ["Mumbai", "New Delhi", "Bangalore", "Kolkata"], answer: 1 },
    { category: "Cities", question: "Which city is known for Times Square?", options: ["Los Angeles", "New York City", "Chicago", "Miami"], answer: 1 },
    { category: "Cities", question: "Which city is the capital of Spain?", options: ["Barcelona", "Valencia", "Madrid", "Seville"], answer: 2 },
    { category: "Cities", question: "Which city is famous for the Acropolis?", options: ["Athens", "Rome", "Istanbul", "Cairo"], answer: 0 },
    { category: "Cities", question: "Which city is the capital of Brazil?", options: ["Rio de Janeiro", "Sao Paulo", "Brasilia", "Salvador"], answer: 2 },
    { category: "Cities", question: "Which city is the largest in China?", options: ["Shanghai", "Beijing", "Hong Kong", "Shenzhen"], answer: 0 },
    { category: "Cities", question: "Which city is known as the 'City of Angels'?", options: ["San Francisco", "New York City", "Los Angeles", "Las Vegas"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of Russia?", options: ["Saint Petersburg", "Moscow", "Kazan", "Sochi"], answer: 1 },
    { category: "Cities", question: "Which city is known for the Great Wall of China?", options: ["Beijing", "Shanghai", "Xi'an", "Chengdu"], answer: 0 },
    { category: "Cities", question: "Which city is home to the Burj Khalifa?", options: ["Dubai", "Abu Dhabi", "Riyadh", "Doha"], answer: 0 },
    { category: "Cities", question: "Which city is the capital of Italy?", options: ["Rome", "Milan", "Naples", "Venice"], answer: 0 },
    { category: "Cities", question: "Which city is known for the Sydney Opera House?", options: ["Melbourne", "Brisbane", "Sydney", "Canberra"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of South Korea?", options: ["Seoul", "Busan", "Incheon", "Daegu"], answer: 0 },
    { category: "Cities", question: "Which city is famous for Christ the Redeemer?", options: ["Brasilia", "Sao Paulo", "Rio de Janeiro", "Salvador"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of the United Kingdom?", options: ["Manchester", "Edinburgh", "London", "Birmingham"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of Mexico?", options: ["Guadalajara", "Monterrey", "Mexico City", "Tijuana"], answer: 2 },
    { category: "Cities", question: "Which city is known for its famous carnival?", options: ["Barcelona", "Rio de Janeiro", "Venice", "New Orleans"], answer: 1 },
    { category: "Cities", question: "Which city is known as the 'Windy City'?", options: ["New York", "Chicago", "Boston", "San Francisco"], answer: 1 },
    { category: "Cities", question: "Which city is the capital of Argentina?", options: ["Buenos Aires", "Rosario", "Cordoba", "Mendoza"], answer: 0 },
    { category: "Cities", question: "Which city is famous for the Leaning Tower?", options: ["Florence", "Venice", "Rome", "Pisa"], answer: 3 },
    { category: "Cities", question: "Which city is the capital of South Africa?", options: ["Cape Town", "Johannesburg", "Pretoria", "Durban"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], answer: 3 },
    { category: "Cities", question: "Which city is famous for the Statue of Liberty?", options: ["Los Angeles", "San Francisco", "New York City", "Washington D.C."], answer: 2 },
    { category: "Cities", question: "Which city is known as the 'Eternal City'?", options: ["Athens", "Rome", "Istanbul", "Jerusalem"], answer: 1 },
    { category: "Cities", question: "Which city is the capital of Turkey?", options: ["Istanbul", "Ankara", "Izmir", "Bursa"], answer: 1 },
    { category: "Cities", question: "Which city is known for the Blue Mosque?", options: ["Dubai", "Istanbul", "Cairo", "Athens"], answer: 1 },
    { category: "Cities", question: "Which city is the capital of Norway?", options: ["Oslo", "Bergen", "Stockholm", "Copenhagen"], answer: 0 },
    { category: "Cities", question: "Which city is the capital of Thailand?", options: ["Bangkok", "Phuket", "Chiang Mai", "Pattaya"], answer: 0 },
    { category: "Cities", question: "Which city is famous for Oktoberfest?", options: ["Berlin", "Frankfurt", "Munich", "Hamburg"], answer: 2 },
    { category: "Cities", question: "Which city is the capital of Portugal?", options: ["Lisbon", "Porto", "Madrid", "Seville"], answer: 0 },
    { category: "Cities", question: "Which city is home to the Kremlin?", options: ["Moscow", "Saint Petersburg", "Kiev", "Warsaw"], answer: 0 },
    { category: "Cities", question: "Which city is famous for the Brandenburg Gate?", options: ["Vienna", "Berlin", "Amsterdam", "Copenhagen"], answer: 1 },
    { category: "Cities", question: "Which city is the capital of Greece?", options: ["Rome", "Athens", "Istanbul", "Cairo"], answer: 1 },
    { category: "Cities", question: "Which city is known for the Taj Mahal?", options: ["Mumbai", "New Delhi", "Agra", "Jaipur"], answer: 2 },          
 
    { category: "Geography", question: "What is the largest continent?", options: ["Africa", "Asia", "Europe", "North America"], answer: 1 },
    { category: "Geography", question: "Which is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], answer: 1 },
    { category: "Geography", question: "Which is the smallest country in the world?", options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], answer: 2 },
    { category: "Geography", question: "What is the highest mountain in the world?", options: ["K2", "Mount Everest", "Mount Kilimanjaro", "Denali"], answer: 1 },
    { category: "Geography", question: "Which ocean is the largest?", options: ["Indian Ocean", "Atlantic Ocean", "Arctic Ocean", "Pacific Ocean"], answer: 3 },
    { category: "Geography", question: "Which desert is the largest in the world?", options: ["Sahara", "Gobi", "Antarctic", "Arabian"], answer: 2 },
    { category: "Geography", question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2 },
    { category: "Geography", question: "Which country has the most population?", options: ["India", "China", "USA", "Indonesia"], answer: 1 },
    { category: "Geography", question: "Which country is the largest by area?", options: ["Canada", "USA", "Russia", "China"], answer: 2 },
    { category: "Geography", question: "Which river flows through Egypt?", options: ["Nile", "Amazon", "Ganges", "Yangtze"], answer: 0 },
    { category: "Geography", question: "Which is the coldest continent on Earth?", options: ["Asia", "Europe", "Antarctica", "North America"], answer: 2 },
    { category: "Geography", question: "Which country has the most time zones?", options: ["Russia", "USA", "China", "France"], answer: 3 },
    { category: "Geography", question: "Which sea is located between Europe and Africa?", options: ["Caribbean", "Red Sea", "Mediterranean", "Black Sea"], answer: 2 },
    { category: "Geography", question: "Which river is the longest in Europe?", options: ["Danube", "Volga", "Rhine", "Seine"], answer: 1 },
    { category: "Geography", question: "Which country is known as the Land of the Rising Sun?", options: ["China", "Japan", "South Korea", "Vietnam"], answer: 1 },
    { category: "Geography", question: "Which is the largest island in the world?", options: ["Greenland", "Australia", "New Guinea", "Borneo"], answer: 0 },
    { category: "Geography", question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], answer: 3 },
    { category: "Geography", question: "Which is the largest lake in the world?", options: ["Lake Victoria", "Caspian Sea", "Lake Superior", "Lake Baikal"], answer: 1 },
    { category: "Geography", question: "What is the capital of Brazil?", options: ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"], answer: 0 },
    { category: "Geography", question: "Which country is home to the Eiffel Tower?", options: ["Spain", "France", "Italy", "Germany"], answer: 1 },
    { category: "Geography", question: "Which U.S. state is the largest by area?", options: ["Texas", "California", "Alaska", "Montana"], answer: 2 },
    { category: "Geography", question: "What is the capital of South Africa?", options: ["Johannesburg", "Cape Town", "Pretoria", "Durban"], answer: 2 },
    { category: "Geography", question: "What is the capital of Russia?", options: ["Moscow", "Saint Petersburg", "Kazan", "Novosibirsk"], answer: 0 },
    { category: "Geography", question: "Which ocean is on the west coast of the United States?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], answer: 2 },
    { category: "Geography", question: "Which mountain range is the longest?", options: ["Rocky Mountains", "Himalayas", "Andes", "Alps"], answer: 2 },
    { category: "Geography", question: "Which country is the home of the Amazon rainforest?", options: ["Brazil", "Colombia", "Peru", "Venezuela"], answer: 0 },
    { category: "Geography", question: "Which country has the most volcanoes?", options: ["Indonesia", "Japan", "USA", "Iceland"], answer: 0 },
    { category: "Geography", question: "Which is the smallest continent by area?", options: ["Europe", "Australia", "Antarctica", "South America"], answer: 1 },
    { category: "Geography", question: "What is the capital of Italy?", options: ["Milan", "Venice", "Rome", "Naples"], answer: 2 },
    { category: "Geography", question: "What is the capital of Egypt?", options: ["Cairo", "Alexandria", "Luxor", "Giza"], answer: 0 },
    { category: "Geography", question: "What is the second largest country by area?", options: ["USA", "Russia", "Canada", "China"], answer: 2 },
    { category: "Geography", question: "What is the tallest waterfall in the world?", options: ["Niagara Falls", "Angel Falls", "Victoria Falls", "Yosemite Falls"], answer: 1 },
    { category: "Geography", question: "Which country is known for Mount Fuji?", options: ["China", "Japan", "South Korea", "Vietnam"], answer: 1 },
    { category: "Geography", question: "What is the capital of Argentina?", options: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza"], answer: 0 },
    { category: "Geography", question: "Which continent has the most countries?", options: ["Asia", "Europe", "Africa", "South America"], answer: 2 },
    { category: "Geography", question: "What is the capital of Mexico?", options: ["Guadalajara", "Cancun", "Mexico City", "Monterrey"], answer: 2 },
    { category: "Geography", question: "Which river is the longest in South America?", options: ["Amazon", "Parana", "Orinoco", "Magdalena"], answer: 0 },
    { category: "Geography", question: "What is the largest country in Africa?", options: ["Sudan", "Algeria", "Nigeria", "Egypt"], answer: 1 },
    { category: "Geography", question: "Which U.S. state is known as the Sunshine State?", options: ["California", "Florida", "Hawaii", "Texas"], answer: 1 },
    { category: "Geography", question: "What is the highest mountain in Africa?", options: ["Mount Kenya", "Mount Kilimanjaro", "Mount Elgon", "Mount Meru"], answer: 1 },
    { category: "Geography", question: "Which country shares the longest border with the USA?", options: ["Mexico", "Canada", "Russia", "Cuba"], answer: 1 },
    { category: "Geography", question: "Which desert is the hottest in the world?", options: ["Gobi", "Sahara", "Kalahari", "Mojave"], answer: 1 },
    { category: "Geography", question: "Which European country has the most islands?", options: ["Norway", "Sweden", "Greece", "Finland"], answer: 1 },
    { category: "Geography", question: "What is the longest river in North America?", options: ["Mississippi", "Missouri", "Colorado", "Rio Grande"], answer: 0 },
    { category: "Geography", question: "Which country is home to the Great Barrier Reef?", options: ["New Zealand", "Australia", "Indonesia", "Philippines"], answer: 1 },
    { category: "Geography", question: "Which continent is the driest?", options: ["Asia", "Africa", "Australia", "Antarctica"], answer: 3 },
    { category: "Geography", question: "Which country is known as the land of fire and ice?", options: ["Finland", "Iceland", "Greenland", "Norway"], answer: 1 },
    { category: "Geography", question: "Which European city is known as the 'City of Canals'?", options: ["Venice", "Amsterdam", "Bruges", "Stockholm"], answer: 0 },

    { category: "History", question: "Who was the first president of the United States?", options: ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"], answer: 2 },
    { category: "History", question: "In which year did the Titanic sink?", options: ["1912", "1905", "1898", "1920"], answer: 0 },
    { category: "History", question: "Which war was fought between the North and the South in the U.S.?", options: ["World War I", "American Civil War", "Revolutionary War", "Vietnam War"], answer: 1 },
    { category: "History", question: "Which empire was ruled by Julius Caesar?", options: ["Greek Empire", "Roman Empire", "Ottoman Empire", "Byzantine Empire"], answer: 1 },
    { category: "History", question: "Who discovered America?", options: ["Christopher Columbus", "Leif Erikson", "James Cook", "Ferdinand Magellan"], answer: 0 },
    { category: "History", question: "What year did World War II end?", options: ["1939", "1941", "1945", "1950"], answer: 2 },
    { category: "History", question: "Which civilization built the pyramids?", options: ["Romans", "Greeks", "Egyptians", "Mesopotamians"], answer: 2 },
    { category: "History", question: "What year did the Berlin Wall fall?", options: ["1989", "1961", "1975", "1990"], answer: 0 },
    { category: "History", question: "Who was the first man to walk on the moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "John Glenn"], answer: 2 },
    { category: "History", question: "Which country was Adolf Hitler born in?", options: ["Germany", "Austria", "Poland", "Hungary"], answer: 1 },
    { category: "History", question: "Who was the British Prime Minister during World War II?", options: ["Winston Churchill", "Neville Chamberlain", "Margaret Thatcher", "Tony Blair"], answer: 0 },
    { category: "History", question: "What was the name of the ship that brought the Pilgrims to America?", options: ["Santa Maria", "Mayflower", "Endeavour", "Beagle"], answer: 1 },
    { category: "History", question: "Which event started World War I?", options: ["Invasion of Poland", "Assassination of Archduke Ferdinand", "Sinking of Lusitania", "Pearl Harbor"], answer: 1 },
    { category: "History", question: "Which civilization invented democracy?", options: ["Romans", "Greeks", "Egyptians", "Persians"], answer: 1 },
    { category: "History", question: "Who was the first female Prime Minister of the UK?", options: ["Margaret Thatcher", "Theresa May", "Angela Merkel", "Golda Meir"], answer: 0 },
    { category: "History", question: "Which country was responsible for the bombing of Pearl Harbor?", options: ["Germany", "Japan", "Italy", "Russia"], answer: 1 },
    { category: "History", question: "Which document declared the independence of the American colonies?", options: ["Bill of Rights", "Constitution", "Declaration of Independence", "Federalist Papers"], answer: 2 },
    { category: "History", question: "Who was the leader of the Soviet Union during World War II?", options: ["Lenin", "Stalin", "Trotsky", "Khrushchev"], answer: 1 },
    { category: "History", question: "Which country built the Berlin Wall?", options: ["West Germany", "United States", "East Germany", "Soviet Union"], answer: 2 },
    { category: "History", question: "Who was known as the Maid of Orleans?", options: ["Elizabeth I", "Cleopatra", "Joan of Arc", "Catherine the Great"], answer: 2 },
    { category: "History", question: "Who was the first emperor of China?", options: ["Confucius", "Qin Shi Huang", "Kublai Khan", "Sun Tzu"], answer: 1 },
    { category: "History", question: "Which empire was known for its roads and aqueducts?", options: ["Greek Empire", "Roman Empire", "Persian Empire", "Ottoman Empire"], answer: 1 },
    { category: "History", question: "Which U.S. president issued the Emancipation Proclamation?", options: ["George Washington", "Abraham Lincoln", "Franklin D. Roosevelt", "Andrew Jackson"], answer: 1 },
    { category: "History", question: "Which country was invaded during the start of World War II?", options: ["France", "Poland", "Austria", "Czechoslovakia"], answer: 1 },
    { category: "History", question: "Who painted the Mona Lisa?", options: ["Michelangelo", "Donatello", "Leonardo da Vinci", "Raphael"], answer: 2 },
    { category: "History", question: "Which civilization built Machu Picchu?", options: ["Aztecs", "Incas", "Mayans", "Olmecs"], answer: 1 },
    { category: "History", question: "What was the name of the first successful English colony in America?", options: ["Jamestown", "Plymouth", "Roanoke", "Salem"], answer: 0 },
    { category: "History", question: "Who was the first European to reach India by sea?", options: ["Christopher Columbus", "Marco Polo", "Vasco da Gama", "Ferdinand Magellan"], answer: 2 },
    { category: "History", question: "Which U.S. state was the last to abolish slavery?", options: ["New York", "Texas", "Mississippi", "Georgia"], answer: 1 },
    { category: "History", question: "Who was the leader of Nazi Germany?", options: ["Benito Mussolini", "Joseph Stalin", "Adolf Hitler", "Winston Churchill"], answer: 2 },
    { category: "History", question: "Which revolution led to the rise of the Soviet Union?", options: ["American Revolution", "Russian Revolution", "French Revolution", "Industrial Revolution"], answer: 1 },
    { category: "History", question: "Who was the first man to circumnavigate the Earth?", options: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "Francis Drake"], answer: 2 },
    { category: "History", question: "Which battle marked Napoleon's final defeat?", options: ["Battle of Waterloo", "Battle of Trafalgar", "Battle of Leipzig", "Battle of Austerlitz"], answer: 0 },
    { category: "History", question: "What was the name of the project that developed the atomic bomb?", options: ["Manhattan Project", "Trinity Project", "Apollo Project", "Enola Gay Project"], answer: 0 },
    { category: "History", question: "Which king signed the Magna Carta?", options: ["King Henry VIII", "King John", "King George III", "King Edward I"], answer: 1 },
    { category: "History", question: "Which U.S. president resigned because of the Watergate scandal?", options: ["John F. Kennedy", "Gerald Ford", "Richard Nixon", "Jimmy Carter"], answer: 2 },
    { category: "History", question: "Who was the longest-reigning British monarch?", options: ["Queen Victoria", "Queen Elizabeth II", "King George III", "Queen Mary I"], answer: 1 },
    { category: "History", question: "Which ancient civilization is famous for the pyramids?", options: ["Romans", "Greeks", "Egyptians", "Sumerians"], answer: 2 },
    { category: "History", question: "Who was assassinated in Sarajevo in 1914, sparking World War I?", options: ["Franz Ferdinand", "Wilhelm II", "Gavrilo Princip", "Nicholas II"], answer: 0 },
    { category: "History", question: "Who was the first U.S. president to be impeached?", options: ["Richard Nixon", "Bill Clinton", "Andrew Johnson", "Donald Trump"], answer: 2 },
    { category: "History", question: "Which empire did the Ottomans conquer in 1453?", options: ["Roman Empire", "Persian Empire", "Byzantine Empire", "Mongol Empire"], answer: 2 },
    { category: "History", question: "Who wrote the Communist Manifesto?", options: ["Karl Marx", "Vladimir Lenin", "Friedrich Engels", "Leon Trotsky"], answer: 0 },
    { category: "History", question: "Who led the independence movement in India?", options: ["Subhas Chandra Bose", "Mahatma Gandhi", "Jawaharlal Nehru", "Indira Gandhi"], answer: 1 },
    { category: "History", question: "Which war was known as the 'Great War'?", options: ["American Civil War", "World War I", "World War II", "Vietnam War"], answer: 1 },
    { category: "History", question: "Which country gifted the Statue of Liberty to the U.S.?", options: ["France", "United Kingdom", "Spain", "Italy"], answer: 0 },
    { category: "History", question: "Who was the first U.S. president to be elected for two non-consecutive terms?", options: ["George Washington", "Abraham Lincoln", "Grover Cleveland", "Franklin D. Roosevelt"], answer: 2 },
    { category: "History", question: "Which empire was known for the Code of Hammurabi?", options: ["Roman Empire", "Greek Empire", "Babylonian Empire", "Egyptian Empire"], answer: 2 },

    { category: "Sports", question: "Which country has won the most FIFA World Cup titles?", options: ["Germany", "Italy", "Brazil", "Argentina"], answer: 2 },
    { category: "Sports", question: "In which year did Michael Jordan retire for the last time?", options: ["1999", "2003", "1998", "2001"], answer: 1 },
    { category: "Sports", question: "Which sport is known as the 'King of Sports'?", options: ["Basketball", "Football", "Tennis", "Cricket"], answer: 1 },
    { category: "Sports", question: "Which country hosted the 2016 Summer Olympics?", options: ["China", "Brazil", "UK", "USA"], answer: 1 },
    { category: "Sports", question: "Which is the oldest tennis tournament in the world?", options: ["US Open", "Australian Open", "Wimbledon", "French Open"], answer: 2 },
    { category: "Sports", question: "Which NFL team has won the most Super Bowl titles?", options: ["Pittsburgh Steelers", "Dallas Cowboys", "New England Patriots", "San Francisco 49ers"], answer: 2 },
    { category: "Sports", question: "Which player holds the record for most goals in a single World Cup?", options: ["Pelé", "Ronaldo", "Just Fontaine", "Miroslav Klose"], answer: 2 },
    { category: "Sports", question: "Which country is known for dominating the sport of rugby?", options: ["England", "New Zealand", "Australia", "South Africa"], answer: 1 },
    { category: "Sports", question: "Which NBA team has won the most championships?", options: ["Los Angeles Lakers", "Chicago Bulls", "Boston Celtics", "Golden State Warriors"], answer: 2 },
    { category: "Sports", question: "Which country is home to the Formula 1 Monaco Grand Prix?", options: ["France", "Monaco", "Italy", "Spain"], answer: 1 },
    { category: "Sports", question: "Who holds the record for the most home runs in MLB history?", options: ["Babe Ruth", "Hank Aaron", "Barry Bonds", "Willie Mays"], answer: 2 },
    { category: "Sports", question: "Which boxer is known as 'The Greatest'?", options: ["Mike Tyson", "Muhammad Ali", "Floyd Mayweather", "Joe Frazier"], answer: 1 },
    { category: "Sports", question: "Which country has won the most Olympic gold medals in history?", options: ["Russia", "China", "Germany", "USA"], answer: 3 },
    { category: "Sports", question: "Which team won the 2020 UEFA Champions League?", options: ["Barcelona", "Bayern Munich", "Paris Saint-Germain", "Liverpool"], answer: 1 },
    { category: "Sports", question: "Which golfer has won the most major championships?", options: ["Tiger Woods", "Phil Mickelson", "Jack Nicklaus", "Arnold Palmer"], answer: 2 },
    { category: "Sports", question: "Which country won the Cricket World Cup in 2019?", options: ["India", "Australia", "England", "New Zealand"], answer: 2 },
    { category: "Sports", question: "Which tennis player has won the most Grand Slam titles?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"], answer: 2 },
    { category: "Sports", question: "Which city hosted the 2012 Summer Olympics?", options: ["Beijing", "Athens", "London", "Rio de Janeiro"], answer: 2 },
    { category: "Sports", question: "Which country is known for its dominance in ice hockey?", options: ["USA", "Russia", "Sweden", "Canada"], answer: 3 },
    { category: "Sports", question: "Which swimmer holds the record for the most Olympic medals?", options: ["Ian Thorpe", "Mark Spitz", "Michael Phelps", "Ryan Lochte"], answer: 2 },
    { category: "Sports", question: "Which team won the FIFA World Cup in 2018?", options: ["Brazil", "France", "Germany", "Argentina"], answer: 1 },
    { category: "Sports", question: "Which athlete holds the world record for the 100 meters sprint?", options: ["Carl Lewis", "Usain Bolt", "Tyson Gay", "Yohan Blake"], answer: 1 },
    { category: "Sports", question: "Which country has won the most Tour de France titles?", options: ["USA", "France", "Spain", "Belgium"], answer: 1 },
    { category: "Sports", question: "Which country has hosted the most Olympic Games?", options: ["Japan", "USA", "Germany", "France"], answer: 1 },
    { category: "Sports", question: "Which team won the NBA championship in 2020?", options: ["Golden State Warriors", "Miami Heat", "Los Angeles Lakers", "Toronto Raptors"], answer: 2 },
    { category: "Sports", question: "Which footballer has won the most Ballon d'Or awards?", options: ["Cristiano Ronaldo", "Lionel Messi", "Johan Cruyff", "Michel Platini"], answer: 1 },
    { category: "Sports", question: "Which country won the Rugby World Cup in 2019?", options: ["New Zealand", "Australia", "England", "South Africa"], answer: 3 },
    { category: "Sports", question: "Which tennis player won all four Grand Slams in 1988?", options: ["Serena Williams", "Martina Navratilova", "Steffi Graf", "Monica Seles"], answer: 2 },
    { category: "Sports", question: "Which country is home to the football club FC Barcelona?", options: ["Italy", "Spain", "Portugal", "France"], answer: 1 },
    { category: "Sports", question: "Which boxer was undefeated in his professional career?", options: ["Muhammad Ali", "Mike Tyson", "Floyd Mayweather", "Joe Frazier"], answer: 2 },
    { category: "Sports", question: "Which country hosted the 2018 Winter Olympics?", options: ["Canada", "South Korea", "Japan", "Russia"], answer: 1 },
    { category: "Sports", question: "Which footballer is known as 'The King'?", options: ["Diego Maradona", "Cristiano Ronaldo", "Pelé", "Zinedine Zidane"], answer: 2 },
    { category: "Sports", question: "Which NBA player has the most career points?", options: ["Michael Jordan", "Kobe Bryant", "LeBron James", "Kareem Abdul-Jabbar"], answer: 3 },
    { category: "Sports", question: "Which country has won the most World Series titles?", options: ["Canada", "Cuba", "USA", "Japan"], answer: 2 },
    { category: "Sports", question: "Which footballer scored the 'Hand of God' goal?", options: ["Lionel Messi", "Cristiano Ronaldo", "Diego Maradona", "Ronaldinho"], answer: 2 },
    { category: "Sports", question: "Which athlete has won the most gold medals at a single Olympic Games?", options: ["Carl Lewis", "Usain Bolt", "Michael Phelps", "Mark Spitz"], answer: 2 },
    { category: "Sports", question: "Which team won the Stanley Cup in 2021?", options: ["Boston Bruins", "Tampa Bay Lightning", "Montreal Canadiens", "Vegas Golden Knights"], answer: 1 },
    { category: "Sports", question: "Which country has won the most Davis Cup tennis titles?", options: ["Spain", "USA", "Australia", "France"], answer: 1 },
    { category: "Sports", question: "Which NFL team won the 2021 Super Bowl?", options: ["Kansas City Chiefs", "New England Patriots", "Tampa Bay Buccaneers", "San Francisco 49ers"], answer: 2 },
    { category: "Sports", question: "Which country has won the most Cricket World Cup titles?", options: ["India", "Australia", "West Indies", "Pakistan"], answer: 1 },
    { category: "Sports", question: "Which team has won the most FIFA Women's World Cup titles?", options: ["Brazil", "USA", "Germany", "Norway"], answer: 1 },
    { category: "Sports", question: "Which tennis player has won the most Australian Open titles?", options: ["Rafael Nadal", "Novak Djokovic", "Roger Federer", "Andy Murray"], answer: 1 },
    { category: "Sports", question: "Which country won the Euro 2016 football championship?", options: ["Germany", "Portugal", "Spain", "France"], answer: 1 },
    { category: "Sports", question: "Which team won the 2021 NBA Finals?", options: ["Phoenix Suns", "Milwaukee Bucks", "Brooklyn Nets", "Los Angeles Lakers"], answer: 1 },
    { category: "Sports", question: "Which golfer won the 2021 Masters Tournament?", options: ["Dustin Johnson", "Hideki Matsuyama", "Jordan Spieth", "Tiger Woods"], answer: 1 },
    { category: "Sports", question: "Which country hosted the 1998 FIFA World Cup?", options: ["Brazil", "USA", "France", "Germany"], answer: 2 },

        { category: "Astrology", question: "Which planet is known as the Red Planet?", options: ["Earth", "Mars", "Jupiter", "Venus"], answer: 1 },
        { category: "Astrology", question: "Which is the largest planet in our solar system?", options: ["Saturn", "Earth", "Jupiter", "Neptune"], answer: 2 },
        { category: "Astrology", question: "What is the name of Earth's galaxy?", options: ["Andromeda", "Milky Way", "Sombrero", "Whirlpool"], answer: 1 },
        { category: "Astrology", question: "Which planet is known for its rings?", options: ["Saturn", "Jupiter", "Uranus", "Neptune"], answer: 0 },
        { category: "Astrology", question: "Which planet is closest to the Sun?", options: ["Venus", "Mars", "Mercury", "Earth"], answer: 2 },
        { category: "Astrology", question: "Which star is the brightest in the night sky?", options: ["Vega", "Sirius", "Betelgeuse", "Polaris"], answer: 1 },
        { category: "Astrology", question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], answer: 1 },
        { category: "Astrology", question: "Which planet is often called Earth's twin?", options: ["Mars", "Venus", "Mercury", "Jupiter"], answer: 1 },
        { category: "Astrology", question: "What is the name of the second largest planet in the solar system?", options: ["Saturn", "Jupiter", "Neptune", "Earth"], answer: 0 },
        { category: "Astrology", question: "What is the name of the dwarf planet located in the asteroid belt?", options: ["Pluto", "Ceres", "Eris", "Haumea"], answer: 1 },
        { category: "Astrology", question: "Which planet has the most moons?", options: ["Earth", "Jupiter", "Mars", "Saturn"], answer: 1 },
        { category: "Astrology", question: "Which planet is tilted on its side?", options: ["Neptune", "Mars", "Uranus", "Saturn"], answer: 2 },
        { category: "Astrology", question: "Which planet has the shortest day?", options: ["Venus", "Jupiter", "Mars", "Saturn"], answer: 1 },
        { category: "Astrology", question: "What is the name of the largest moon of Saturn?", options: ["Titan", "Europa", "Ganymede", "Callisto"], answer: 0 },
        { category: "Astrology", question: "What is the closest star to Earth?", options: ["Alpha Centauri", "Sirius", "Proxima Centauri", "Vega"], answer: 2 },
        { category: "Astrology", question: "Which constellation is known as the hunter?", options: ["Orion", "Draco", "Cassiopeia", "Leo"], answer: 0 },
        { category: "Astrology", question: "Which planet is the hottest in our solar system?", options: ["Venus", "Mercury", "Mars", "Earth"], answer: 0 },
        { category: "Astrology", question: "Which planet is farthest from the Sun?", options: ["Neptune", "Pluto", "Uranus", "Saturn"], answer: 0 },
        { category: "Astrology", question: "What is the name of the comet that is visible from Earth every 75-76 years?", options: ["Hale-Bopp", "Halley's Comet", "Swift-Tuttle", "Encke's Comet"], answer: 1 },
        { category: "Astrology", question: "What type of celestial object is the Sun?", options: ["Planet", "Star", "Asteroid", "Comet"], answer: 1 },
        { category: "Astrology", question: "What is the surface temperature of the Sun?", options: ["6,000°C", "15,000°C", "10,000°C", "2,000°C"], answer: 0 },
        { category: "Astrology", question: "Which gas is most abundant in the Sun?", options: ["Helium", "Oxygen", "Hydrogen", "Nitrogen"], answer: 2 },
        { category: "Astrology", question: "What is the closest galaxy to the Milky Way?", options: ["Andromeda", "Triangulum", "Magellanic Clouds", "Sombrero"], answer: 0 },
        { category: "Astrology", question: "What is a supernova?", options: ["A black hole", "An exploding star", "A new star", "A meteor impact"], answer: 1 },
        { category: "Astrology", question: "Which space probe was the first to leave our solar system?", options: ["Voyager 1", "Pioneer 10", "New Horizons", "Voyager 2"], answer: 0 },
        { category: "Astrology", question: "How long does it take for light from the Sun to reach Earth?", options: ["8 minutes", "1 minute", "30 seconds", "12 minutes"], answer: 0 },
        { category: "Astrology", question: "What is the Kuiper Belt?", options: ["A galaxy", "A group of asteroids", "A region of icy objects", "A star cluster"], answer: 2 },
        { category: "Astrology", question: "Which planet has the Great Red Spot?", options: ["Mars", "Jupiter", "Saturn", "Uranus"], answer: 1 },
        { category: "Astrology", question: "What is the name of the largest volcano in the solar system?", options: ["Mount Everest", "Olympus Mons", "Vesuvius", "Mauna Kea"], answer: 1 },
        { category: "Astrology", question: "Which is the only planet that rotates clockwise?", options: ["Mars", "Earth", "Venus", "Mercury"], answer: 2 },
        { category: "Astrology", question: "Which celestial body is known as Earth's natural satellite?", options: ["Venus", "Mars", "Moon", "Sun"], answer: 2 },
        { category: "Astrology", question: "What is the name of the closest black hole to Earth?", options: ["Sagittarius A*", "Cygnus X-1", "Ton 618", "GRO J1655-40"], answer: 1 },
        { category: "Astrology", question: "How many Earths can fit inside Jupiter?", options: ["100", "500", "1,300", "1,000"], answer: 2 },
        { category: "Astrology", question: "Which planet is known as the Morning Star?", options: ["Mars", "Mercury", "Venus", "Jupiter"], answer: 2 },
        { category: "Astrology", question: "What is the main component of Saturn's rings?", options: ["Rock", "Ice", "Dust", "Gas"], answer: 1 },
        { category: "Astrology", question: "What is the event horizon?", options: ["The edge of a black hole", "A star's corona", "A comet's tail", "A galaxy's center"], answer: 0 },
        { category: "Astrology", question: "Which planet has a day longer than its year?", options: ["Venus", "Neptune", "Mercury", "Uranus"], answer: 0 },
        { category: "Astrology", question: "Which dwarf planet was once considered the ninth planet?", options: ["Eris", "Ceres", "Haumea", "Pluto"], answer: 3 },
        { category: "Astrology", question: "Which planet's moon is named Titan?", options: ["Saturn", "Jupiter", "Neptune", "Uranus"], answer: 0 },
        { category: "Astrology", question: "What is the speed of light?", options: ["150,000 km/s", "300,000 km/s", "250,000 km/s", "200,000 km/s"], answer: 1 },
        { category: "Astrology", question: "How many constellations are officially recognized?", options: ["88", "75", "90", "99"], answer: 0 },
        { category: "Astrology", question: "Which planet is home to the largest canyon in the solar system?", options: ["Mars", "Earth", "Venus", "Jupiter"], answer: 0 },
        { category: "Astrology", question: "Which space telescope was launched in 1990?", options: ["Spitzer", "Kepler", "James Webb", "Hubble"], answer: 3 },
        { category: "Astrology", question: "What is a pulsar?", options: ["A rotating neutron star", "A comet", "A supermassive black hole", "A galaxy"], answer: 0 },
        { category: "Astrology", question: "Which planet has the fastest winds in the solar system?", options: ["Neptune", "Jupiter", "Saturn", "Uranus"], answer: 0 },
        { category: "Astrology", question: "Which planet has two moons, Phobos and Deimos?", options: ["Mercury", "Mars", "Venus", "Jupiter"], answer: 1 },
        { category: "Astrology", question: "How long does it take the Earth to orbit the Sun?", options: ["24 hours", "365 days", "30 days", "100 days"], answer: 1 },
        { category: "Astrology", question: "What are shooting stars?", options: ["Comets", "Meteoroids", "Stars", "Asteroids"], answer: 1 },      
];
